CREATE DATABASE mini DEFAULT CHARACTER SET 'utf8';
USE mini;
CREATE TABLE mini_users(
	id SMALLINT UNSIGNED NOT NULL KEY AUTO_INCREMENT,
	username VARCHAR(30) NOT NULL UNIQUE,
	password VARCHAR(32) NOT NULL
);
CREATE TABLE mini_products(
	id INT UNSIGNED NOT NULL KEY AUTO_INCREMENT,
	productname VARCHAR(80) NOT NULL,
	saleprice DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT 0,
	thumb VARCHAR(50) NOT NULL
);
CREATE TABLE mini_shopping(
	id INT UNSIGNED NOT NULL KEY AUTO_INCREMENT,
	user_id SMALLINT UNSIGNED NOT NULL,
	product_id INT UNSIGNED NOT NULL,
	product_num SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	FOREIGN KEY (user_id) REFERENCES mini_users(id),
	FOREIGN KEY (product_id) REFERENCES mini_products(id)
);